### ISSUE TITLE
Works on some servers, but not others

### ISSUE THREAD

**Issue by masey9** [pinceladasdaweb/Simple-PHP-Contact-Form#18]
Just quickly, I have noticed that this fantastic form works on my testing server for the clients I use it for, but when I send the files to their live servers, it's a bit of a 50/50 whether the form actually works. 

Is there some kind of server setting dependencies we should be looking out for?

Thank for a great bit of code!

// Rob

**Comment by pinceladasdaweb** [comment]
@masey9 

Webhosts increasingly have their systems set to require the "-f" flag.

So instead of:
mail($emailTo, "=?utf-8?B?".base64_encode($subject)."?=", $body, $headers);

change to:
mail($emailTo, "=?utf-8?B?".base64_encode($subject)."?=", $body, $headers, "-fvalidemailfromaddress@mydomain.com");

Note there is no space between the f and the email address.

validemailfromaddress@mydomain.com must (usually) be a valid email hosted on the domain from which the email is being sent.

-f is an additional parameter used by sendmail (the program many servers use to send mail). Basically it's the "from" address. So why set the from address twice?

According to the PHP manual -f sets the X-envelope sender (who is sending the mail), the address specified by -f is a "trusted user" and will be checked against "/etc/mail/trusted-users".

This helps to mitigate against the mail function being abused. It helps to validate that the mail being sent is really from your domain and not simply using a mail function on your domain (in practice the "real" from address will be what is specified by -f as opposed to what you specify in the $from field.)

**Comment by masey9** [comment]
Thanks for that thorough explanation. I gave it a go, still with no luck. 

Could it be that PHPINFO shows that the hosting company have the PHP setting:

mail.add_x_header

...set to "Off"? It's all I can find that would account for why the emails aren't coming through.

**Comment by pinceladasdaweb** [comment]
About mail.add_x_header: http://php.net/manual/en/mail.configuration.php

Do you by chance have access to the mail log function to find out what might be happening?

**Comment by masey9** [comment]
Sadly, no. All they did was place this file on the server and basically tell me to work it out. 

http://www.kozplumbing.com.au/test_email.php

When you load the page, I do, in fact receive an email so whatever they are doing in the code is obviously working. I'm just not sure how to apply that to your code...?

And if it helps, the test form of yours I am running is here:

http://kozplumbing.com.au/contact/mail-test.php

**Comment by martinie** [comment]
Make sure that sendmail is working and you should be OK. I had similar issues.

**Comment by KairusDarkSeeker** [comment]
Same as me when I use hostinger It doesn't work

**Comment by pinceladasdaweb** [comment]
Refatored code. In my tests it worked perfectly in Hotmail, Yahoo, Gmail.
